name: Minecraft Server

on:
 workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    
    steps:
     - name: Install Java and wget
       run: |
         sudo apt-get update
         sudo apt-get install -y openjdk-17-jre-headless wget

     - name: Set up Minecraft Server
       run: |
         mkdir server
         cdserver
         wget https://download.getbukkit.org/spigot/spigot-1.20.1.jar -O server.jar
         echo "eula=true" > eula.txt
         
     - name: Run Minecraft Server
       run: |
         cd server
         java -Xms1G - Xm2G -jar server.jar nogui
