name: Minecraft Server

on:
 workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
     - name: Set up Minecraft Server
       run: |
         sudo apt update
         sudo apt install -y openjdk-17-jre-headless
         mkdir server
         cdserver
         wget https://download.getbukkit.org/spigot/spigot-1.20.1.jar -O server.jar
         echo "eula=true" > eula.txt
         java -Xms1G - Xm2G -jar server.jar nogui
